name: Windows Build

permissions:
  contents: read
  # implicitly all other scopes not listed become none

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# cancel running workflows when new commits are being pushed in pull requests
# but not on the master branch
concurrency:
  group: ${{ github.workflow }} @ ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  windows:
    name: "Windows"
    strategy:
      fail-fast: false

      matrix:
        include:
          - target: shared
            arch: x86_64
            host_os: windows-2022
          - target: static
            arch: x86_64
            host_os: windows-2022
          - target: amalgamation
            arch: x86_64
            host_os: windows-2022

    runs-on: ${{ matrix.host_os }}

    steps:
      - uses: actions/checkout@v4

      - name: Read Repository Configuration
        uses: ./.github/actions/read-repo-config

      - name: Setup Build Agent
        uses: ./.github/actions/setup-build-agent
        with:
          target: ${{ matrix.target }}
          cache-key: ${{ matrix.host_os }}-msvc-${{ matrix.arch }}-${{ matrix.target }}
          arch: ${{ matrix.arch }}

      - name: Build and Test Botan
        run: python3 ./src/scripts/ci_build.py --cc='msvc' --make-tool='ninja' --cpu='${{ matrix.arch }}' --test-results-dir=junit_results ${{ matrix.target }}

      - name: Install Botan
        run: python3 ./src/scripts/install.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Botan-win-${{ matrix.target }}
          path: ${{github.workspace}}
          if-no-files-found: ignore
          include-hidden-files: true
          retention-days: 0
