name: Windows Build

permissions:
  contents: read
  # implicitly all other scopes not listed become none

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  triplet: x64-windows-custom
  
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Install Visual Studio platform toolset
        shell: cmd
        run: |
          "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\setup.exe" modify --quiet --includeRecommended ^
          --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" ^
          --productId Microsoft.VisualStudio.Product.Enterprise ^
          --channelId VisualStudio.15.Release ^
          --add Microsoft.VisualStudio.Component.VC.v141.x86.x64

      - name: Build Botan
        shell: cmd
        run: |
          git clone https://github.com/microsoft/vcpkg
          cd vcpkg
          copy /y /v ${{github.workspace}}\${{ env.triplet }}.cmake triplets
          vcpkg install botan botan:${{ env.triplet }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-artifact
          path: ${{github.workspace}}/vcpkg/installed/${{ env.triplet }}
          if-no-files-found: ignore
          include-hidden-files: true
          retention-days: 0
